import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";

import {GoogleOAuthProvider} from '@react-oauth/google';
import ReduxProviders from "../redux/Provider";
import Header from "./components/header";
import Marquee from "./components/marquee";
import Breadcrumbs from "./components/breadcrumbs";
import Footer from "./components/footer";


// client side
const googleClientId = process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID ?? "";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#F2F4F7] `}
        >
        <GoogleOAuthProvider clientId={googleClientId}>
            <ReduxProviders>
                <Header/>
                <Marquee/>
                <Breadcrumbs/>
                {children}
                <Footer/>
            </ReduxProviders>
        </GoogleOAuthProvider>
        </body>
        </html>
    );
}
